### ISSUE TITLE
memoization (function caching) in squad-client has inconsistent state when using filters

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#104]
https://en.wikipedia.org/wiki/Memoization

A lot of fetching functions in `squad-client` look similar to the following:

```
    __tests__ = None

    def tests(self, count=ALL, **filters):
        if self.__tests__ is None:
            endpoint = '%s%d/tests/' % (self.endpoint, self.id)
            self.__tests__ = self.__fetch__(Test, filters, count, endpoint=endpoint)
        return self.__tests__
```

This type of `function caching` is called `memoization` and can be useful when returning the same values over and over (ie, fibonacci). However, I've found a case where this is not working correctly because I'm using filters and the memoization value is not cached against them.

An example:
```
group = Squad().group("lkft")
project = group.project("linux-next-master")
build = project.build("next-20201214")

test1 = build.tests(environment=2575).values()
# has all tests with environment 2575/arc

test2 = build.tests(environment=2583).values()
# has all tests with environment 2575/arc
# SHOULD HAVE all tests with environment 2583/arm64
```

How did the test suite not catch this?

Because for each test the `setup` function creates a new build object with a reset state. So if I do the following, everything should work

```
group = Squad().group("lkft")
project = group.project("linux-next-master")
build = project.build("next-20201214")

test1 = build.tests(environment=2575).values()
# has all tests with environment 2575/arc

new_build = project.build("next-20201214")
test2 = new_build.tests(environment=2583).values()
# has all tests with environment 2583/arm64
```

This type of functionality is in a lot of places in the code base and needs attention. I'd be happy to discuss what the best option might be to fix the issue and push a fix for it.

**Comment by chaws** [comment]
I think first thing google would tell me is "_Did you mean **memorization**?_"

Yeah, this is clearly a bug if you want to change filters. I'll work on this today
