### ISSUE TITLE
timeouts in ci process when running unit tests

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#150]
There is a 10 second timeout that is occurring when running the squad service migration during testing in CI. We should adjust that timeout to be a little bit longer so we do not have to re-run the ci jobs a number of times to get it to work.

**Comment by chaws** [comment]
Fixed in https://github.com/Linaro/squad-client/commit/eab6f0740171387c438c1d39e5f1e96e830cbbc0
