### ISSUE TITLE
models.py#testjobs does not work with __fetch__ because the TestJob class does not have an id field

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#35]
see here:

https://github.com/Linaro/squad-client/blob/master/squad_client/core/models.py#L44

This means that when you query for jobs you get random UUIDs instead of job ids.

The API defines `job_id` and that likely should be the key used instead. I'm not sure how best to do that. Fix the `squad` api or try and define `id` for the `TestJob` class.

ex:

```
DEBUG:urllib3.connectionpool:https://qa-reports.linaro.org:443 "GET /api/testjobs/?environment=i386&name=lkft-network-basic-tests-master-745&target_build=34782&limit=50 HTTP/1.1" 200 917

{UUID('543acc68-843f-11ea-9bd1-f01898ea9270'): <squad_client.core.models.TestJob object at 0x1105f9af0>}
```

**Comment by jscook2345** [comment]
`job_id` probably does not work here since it seems to map to `lava`. I see that the API is returning some sort of ID.

ex:

https://qa-reports.linaro.org/api/testjobs/2714861/

**Comment by mwasilew** [comment]
@jscook2345 job_id can't be a key as it's not unique. Different LAVA instances (backends in SQUAD naming convention) will produce the same job IDs. Beside that there is a chance some other backends are in use. This is why there is an unique ID for each TestRun object. Proper fix for this:
https://github.com/Linaro/squad/pull/703
Temporarily ID can be retrieved from url field, but I don't think it's a good idea.

**Comment by jscook2345** [comment]
Once I see some jobs with the new ID field I'll follow-up here.

**Comment by chaws** [comment]
Hey @jscook2345 , https://github.com/Linaro/squad/pull/703 is merged and already in production.

```json
GET https://qa-reports.linaro.org/api/testjobs/2714861/
{
    "url": "https://qa-reports.linaro.org/api/testjobs/2714861/",
    "id": 2714861,
    "external_url": "https://lkft.validation.linaro.org/scheduler/job/1352033",
    "definition": "https://qa-reports.linaro.org/api/testjobs/2714861/definition/",
    "name": "lkft-network-basic-tests-master-745",
    "environment": "i386",
    "created_at": "2020-04-08T05:10:15.421076Z",
    "submitted_at": "2020-04-08T05:10:15.933053Z",
    "fetched_at": "2020-04-08T19:23:16.574063Z",
    "submitted": true,
    "fetched": true,
    "fetch_attempts": 0,
    "last_fetch_attempt": "2020-04-08T19:23:14.718021Z",
    "failure": null,
    "can_resubmit": false,
    "resubmitted_count": 0,
    "job_id": "1352033",
    "job_status": "Complete",
    "backend": "https://qa-reports.linaro.org/api/backends/2/",
    "testrun": "https://qa-reports.linaro.org/api/testruns/2552576/",
    "target": "https://qa-reports.linaro.org/api/projects/6/",
    "target_build": "https://qa-reports.linaro.org/api/builds/34782/",
    "parent_job": null
}
```

I'm closing this now, please re-open it if you need extra features.

**Comment by jscook2345** [comment]
Thanks @chaws !
