### ISSUE TITLE
Best way to get the previous build?

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#38]
I see that there is a `status` assigned to a build (ex: https://qa-reports.linaro.org/api/builds/35450/status/), but it does not list what the previous build was. I think that should potentially be included.

**Comment by mwasilew** [comment]
Sounds good. It makes sense to point to the 'baseline' build in case we delete something in the future. This should go to squad, not client.

**Comment by jscook2345** [comment]
https://github.com/Linaro/squad/issues/708
