### ISSUE TITLE
Cannot get a single suite

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#39]
Currently the only method to get a suite is to query all the suites with some filters. That ends up a little messy.

```
suite = Squad().suites(project=6,slug='ltp-syscalls-tests').pop(143)
```

If https://github.com/Linaro/squad/issues/699 was fixed this would 'simplify' to:

```
suite = Squad().suites(id=143).pop(143)
```

We could, instead, add `suite` method to the `Project` object to clean this up a bit.

```
# https://qa-reports.linaro.org/api/groups/3/
group = Squad().group('lkft')

# https://qa-reports.linaro.org/api/projects/6/
project = group.project('linux-next-oe')

suite = project.suite('SUITE SLUG')
suites = project.suites(FILTERS)
```

What do you think?

**Comment by chaws** [comment]
@jscook2345 I just opened a PR to add that, but didn't implement yet `tests()`, method. It turns out that filtering tests by suite in production times out. I already know a way to fix it, will do that later this week in squad

**Comment by chaws** [comment]
Issue opened: https://github.com/Linaro/squad/issues/727

**Comment by chaws** [comment]
@jscook2345 

Just fyi `suite.tests()` will be available after https://github.com/Linaro/squad-client/pull/46
