### ISSUE TITLE
Cache objects

### ISSUE THREAD

**Issue by chaws** [Linaro/squad-client#4]
Create a cache mechanism: sometimes same objects are requested over and over, where instead they could be stored in memory, that'd save up a few HTTP requests

**Comment by jscook2345** [comment]
@danrue had suggested using `requests_cache`. It's not the best caching library, but it might help for more rapid development and testing.

**Comment by jscook2345** [comment]
@chaws @mwasilew 

This would be nice for me as well with building and testing our new reports. I think this should be a higher priority item.

**Comment by chaws** [comment]
Hi @jscook2345 I think we can give it a shot with [KissCache](https://git.lavasoftware.org/ivoire/kisscache). It seems it's easy to get up and running. I'll come up with a WIP next week

Self reminder: all requests in squad-client pass through https://github.com/Linaro/squad-client/blob/master/squad_client/core/api.py#L86

**Comment by danrue** [comment]
kiss cache seems pretty heavy weight for this use-case. Some local caching mechanism is all that is needed. As you say, all requests pass through the same point so I'm not sure why we would add a django/celery/postgres service just for that. And it would just move the http request from one django app to a different django app. We need in memory and/or local caching (like to a sqlite db or similar).

**Comment by mwasilew** [comment]
I don't think KissCache is fit for the job. It's main goal is to reduce amount of downloaded data when we use large files that don't change. This is pretty much opposite of what SQUAD API produces. We generate small files that change often. So IMHO KissCache is just not going to help. We need much smarter caching on both server and client side.

**Comment by chaws** [comment]
@jscook2345 I did it using what you suggested. It's now accepting a `--cache N` argument that caches urls for N seconds.
