### ISSUE TITLE
Add a shortcut function to report on regressions

### ISSUE THREAD

**Issue by amrohassaan** [Linaro/squad-client#45]
Once we have [test comparison exposed via api](https://github.com/Linaro/squad/issues/739) in squad, a shortcut should be added here for producing regression reports.

**Comment by chaws** [comment]
hey @amrohassaan , the issue was closed I guess this could be passed to client as well

**Comment by amrohassaan** [comment]
@chaws yes, this was added to shortcuts already..i will close it.
