### ISSUE TITLE
Could not get list of finished builds

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#53]
The following example was pulling all builds, not just builds with `finished: true` like I expected.

```
SquadApi.configure(url='https://qa-reports.linaro.org/')

group = Squad().group('lkft')

project = group.project('linux-next-oe')

build = Squad().builds(finished=True)
```

**Comment by mwasilew** [comment]
This is going to be tricky. 'finished' is not a db field but a function. I'm not sure how to enable filtering using this property.

**Comment by chaws** [comment]
@jscook2345 you could get that with:

```python
SquadApi.configure(url='https://qa-reports.linaro.org/')

group = Squad().group('lkft')

project = group.project('linux-next-oe')

build = Squad().builds(status__finished=True)
```

**Comment by jscook2345** [comment]
Hey that does work! So does project.builds! Let me update the README!
