### ISSUE TITLE
submit metadata for a build

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#54]
Given our current process of using `squad-client` as our API and `squad` as our data store for generating reports, we were curious if we could add metadata to a build in `squad` using `squad-client`.

As an example:
Last night we generated a report for build XYZ. The next night, if there are no new builds, we do not want to generate a report for XYZ again.

It would be nice if we could add custom metadata to note that a report was created by us so it could be queried later in squad.

Is this possible given the current setup?

cc: @danrue

**Comment by mwasilew** [comment]
@jscook2345 this is a bit tricky. Metadata is (sort of) immutable. It is uploaded with test results and stored in TestRun object. Then when you request Build metadata it's union of all metadata from TestRuns belonging to this build. So the easiest solution would be to upload 'empty' TestRun with only metadata. I don't think it would work right now. 

Alternative is to use one of the existing fields in ProjectStatus (for example 'notified') or add a new field there, i.e user_notified. This would be the easiest solution. Adding metadata at this point is a bit hard.

**Comment by jscook2345** [comment]
Well, we would potentially send many reports based on one build so only having a single field would not work for us.

We could keep the status in aws in dynamo, but we were thinking about keeping all the 'state' in squad.

What do you think a good option for this would be?

@chaws @danrue @mwasilew ?

**Comment by chaws** [comment]
Currently we have DelayedReports for builds: https://qa-reports.linaro.org/api/reports. But these get deleted after one day.

Perhaps reports could be pushed to squad and marked not to be removed?

What do you think @mwasilew ?

**Comment by mwasilew** [comment]
@chaws this can be done right now (I think). There is a TTL field (data_retention_days) in DelayedReport. We can assign 0 'do not remove' meaning. Also viewset needs to be changed to rw (it's ro right now). So the changes are minimal from squad perspective.

The downside of this solution is what I would call lack of transparency. Uploading multiple reports for the same build might be confusing for someone not familiar with the situation. If the reports stay there forever it won't be clear why this is the case.

Overall I think the idea is sane.

**Comment by jscook2345** [comment]
After hearing your thoughts I think it may be better if we just integrate our own small database into things so we can track reports sent out ourselves. Thanks for the feedback!
