### ISSUE TITLE
How to define a suite when manually submitting tests?

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#67]
I'm not able to see how to define a suite when submitting tests either via the command `squad-client submit ...` or using the api calls in `shortcuts.py` or `models.py#TestRun`.

How would I go about doing that?

**Comment by jscook2345** [comment]
for the `result-name` argument, for example, would I just put `suite/test_name`?

**Comment by jscook2345** [comment]
see also / related / maybe duplicate: https://github.com/Linaro/squad-client/issues/68

**Comment by mwasilew** [comment]
@jscook2345 you're correct, what the code does:
```
results_dict = {args.result_name: args.result_value}
```
so when you use suite_name/test_name as parameter for --result-name this will do the job.
