### ISSUE TITLE
squad-client submit failure output should be text

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#70]
See here.

https://gitlab.com/Linaro/lkft/users/justin.cook/mirror-linux-next/-/jobs/765847493

in this case, `squad-client` outputs a bunch of HTML as an error, which is not very useful in a cli environment. Can we convert this to text or something else more readable (json) than raw html?

**Comment by mwasilew** [comment]
For clarity the command line was:
```
squad-client --debug --squad-host=$QA_SERVER --squad-token=$QA_REPORTS_TOKEN submit --group=$QA_TEAM --project=$QA_PROJECT --build=$B --environment='x86' --result-name="build/$CI_JOB_NAME" --result-value="fail"
```

**Comment by chaws** [comment]
@jscook2345 squad's change have been merged and released! I'm closing this issue for now. I think I got all api cases to display a json like `{"detail": "failure reason"}` on squad-client api errors. Please re-open if you find anything else. 

Thanks for reporting!

**Comment by jscook2345** [comment]
@chaws Thanks! Looks great.
