### ISSUE TITLE
test class filter: name is actually short_name

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#80]
Something that caught me today:

```
test = first(self.squad.tests(name="suite/test"))
```

does not filter by `name`, but rather by `short_name`. This was confusing to me. Once I removed the `suite` part of the name the search worked OK.

example that works:
```
test = first(self.squad.tests(name="x86-gcc-9-defconfig-b9979cfa"))
```

example that fails:
```
test = first(self.squad.tests(name="build/x86-gcc-9-defconfig-b9979cfa"))
```

The failure returns `None`. I did verify that it was adding the `suite` and that the `name` field in `squad` was `build/x86-gcc-9-defconfig-b9979cfa`.

**Comment by chaws** [comment]
@jscook2345 you're correct!

Thing is that in Test model there are two attributes `name` and `full_name`, but in the API `name` refers to suite+test name and `short_name` points to test name only. I don't know why it was like that :/, legacy code. So filtering by `"suite/test"` is actually not possible, if you want to filter by suite slug then you should do `test = first(self.squad.tests(suite__slug='suite', name='test'))`.

Does that answer your concern?

**Comment by jscook2345** [comment]
I think knowing how to do the filtering for both suite and test helps. Thanks @chaws !
