### ISSUE TITLE
Write `Build.tests()`

### ISSUE THREAD

**Issue by chaws** [Linaro/squad-client#97]
When This gets merged https://github.com/Linaro/squad/pull/927, squad-client should have the same in the api.

**Comment by jscook2345** [comment]
Sounds great! Also, maybe duplicate of https://github.com/Linaro/squad-client/issues/5 ?

**Comment by chaws** [comment]
Wow, how fast 9 months goes by! It's definitely a duplicate. I was too excited to open this issue here I forgot to check it there was one already. I'm planning on doing this after all data is filled up in prod, probably mid next week

**Comment by chaws** [comment]
Closed in https://github.com/Linaro/squad-client/pull/98
