### ISSUE TITLE
new directory `storage` created when running test suite, not cleaned-up

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#99]
After running the test suite, I noticed that a new directory (`storage`) is created and not cleaned-up.

Contents of `storage`:
```
$ tree storage/
storage/
└── testrun
    ├── 10
    │   └── tests_file
    ├── 11
    │   └── tests_file
    ├── 2
    │   ├── metrics_file
    │   └── tests_file
    ├── 3
    │   ├── log_file
    │   ├── metrics_file
    │   └── tests_file
    ├── 4
    │   ├── log_file
    │   ├── metrics_file
    │   └── tests_file
    ├── 5
    │   └── tests_file
    ├── 6
    │   └── tests_file
    ├── 7
    │   └── metrics_file
    ├── 8
    │   └── tests_file
    └── 9
        └── tests_file

11 directories, 15 files
```

**Comment by mwasilew** [comment]
These come from squad. Are you referring to client unit tests?

**Comment by jscook2345** [comment]
Yes, I think so. I run the `manage.py` command that's in the `.travis.yml` file to test everything.

**Comment by chaws** [comment]
Argh, that's from squad indeed. I'll send a PR to remove those after tests are run.

**Comment by chaws** [comment]
Fixed in https://github.com/Linaro/squad-client/commit/cc8c3d9478480f14355b724eb021266e0647b1e4
